name: Generate and register service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  README_DOCS_VERSION: '1.1.0'

jobs:
  post-deploy:
    name: Post Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LeanIX Secrets ðŸ”’
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Set up JDK temurin 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run gradlew cyclonedxBom task
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: .
          arguments: cyclonedxBom

      - name: VSM discovery
        uses: leanix/vsm-discovery-github-action@v1.0.0
        with:
          api-token: ${{ secrets.VSM_LEANIX_API_TOKEN }}

      - name: Sync github-enterprise-connector.md docs
        uses: readmeio/rdme@7.3.0
        if: github.ref=='refs/heads/main'
        continue-on-error: true
        with:
          rdme: docs ./docs --key=${{ secrets.README_DEVELOPERS_API_KEY }} --version=${{ env.README_DOCS_VERSION }}
